# --- For PHP
#Xdebug client
[[plugins]]
repo = 'joonty/vdebug'
on_ft = 'php'

# --- For HTML/CSS 
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

# hi jade
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'jade'

# Emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

# css3
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

# --- For JavaScript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'js'
