scriptencoding utf-8

" 文字コードの設定
set encoding=utf-8
set fileencodings=utf-8,ucs-bom,iso-2022-jp-3,iso-2022-jp,eucjp-ms,euc-jisx0213,euc-jp,sjis,cp9328
set fileformats=unix,dos,mac

set runtimepath+=~/.config/vim
runtime! init/*.vim
runtime! plugins/*.vim

